
my-snowflake-db:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: oseazbt-booleandata_partner

      # User/password auth
      user: ANJALIN@BOOLEANDATA.COM
      password: Anjali@123
      authenticator: username_password_mfa

      role: DEVELOPER
      database: DEVELOPER_DB
      warehouse: BOOLEAN_DEV_WH
      schema: ANJALI_SCHEMA
      threads: 1
      client_session_keep_alive: False
#      query_tag: [anything]
#
#      # optional
#      connect_retries: 0 # default 0
#      connect_timeout: 10 # default: 10
#      retry_on_database_errors: False # default: false
#      retry_all: False  # default: false